{
    "openapi": "3.0.0",
    "info": {
        "title": "Buyer Organizations",
        "description": "The Bulk Import of Organizations, Cost Centers, and Members facilitates the mass import of Buyer Organizations, Cost Centers, and Members, collectively or individually. It was developed with the purpose of simplifying the management of buyer organizations, allowing for easy updating and maintenance of information.\r\n\r\n## File Structure for Import\r\n\r\n>ℹ ️Only xlsx files under 50MB in size can be imported. Additionally, the file must adhere to the structure outlined below.\r\n\r\nThe import file should be structured with up to three tabs, each serving a distinct purpose:\r\n\r\n### Tabs in the File\r\n\r\n| Tab Name      | Description                                                                                                         |\r\n|---------------|---------------------------------------------------------------------------------------------------------------------|\r\n| Buyer Orgs    | This tab contains detailed information about the buyer organizations. The unique Buyer Org ID helps you identify and manage the organization efficiently.                                                                                                               |\r\n| Cost Centers  | This tab is dedicated to managing cost centers, which are crucial for tracking and controlling organizational costs. It contains information such as the unique identifier (Cost Center ID) and the name of the cost center.                                                                                                               |\r\n| Members       | This tab will store information regarding the members associated with the organizations and cost centers.                                                                                                               |\r\n\r\n### Columns into the Buyer Orgs Tabs\r\n\r\nEach new organization should have one cost center in the Buyer Orgs Tab. Additional columns for each Custom Field configured for the merchant might be added at the end of the Buyer Orgs Tab.\r\n\r\n| Field               | Type   | Description                                                                                     |\r\n|---------------------|--------|-------------------------------------------------------------------------------------------------|\r\n| Buyer Org ID*       | String | A unique identifier for the buyer organization essential for tracking and future updates.       |\r\n| Buyer Org Name*     | String | The official name of the buyer organization.                                                    |\r\n| Admin First Name*   | String | The first name of the administrator overseeing the buyer organization.                          |\r\n| Admin Last Name*    | String | The last name of the administrator overseeing the buyer organization.                           |\r\n| Admin Email*        | String | The administrator's email address serves as the organization's primary point of contact.        |\r\n| Cost Center ID*     | String | A unique identifier for the cost center essential for tracking and future updates.              |\r\n| Cost Center Name*   | String | The name assigned to the cost center.                                                           |\r\n| Address Type*       | String | The classification of the address (e.g., residential, commercial).                              |\r\n| Postal Code*        | String | The postal code corresponding to the address.                                                   |\r\n| Street*             | String | The street name of the address.                                                                 |\r\n| Number*             | String | The numerical identifier for the location (house/building number).                              |\r\n| Complement*         | String | Additional information regarding the address if any.                                            |\r\n| Neighborhood*       | String | The specific neighborhood of the address.                                                       |\r\n| City*               | String | The city where the address is located.                                                          |\r\n| State*              | String | The state where the address is situated.                                                        |\r\n| Country*            | String | The country of the address.                                                                     |\r\n| Receiver Name*      | String | The name of the individual who is the point of contact at the address.                         |\r\n| Phone Number*       | String | The contact number for the receiver.                                                            |\r\n| Business Document*  | String | A document that contains essential business information (e.g., tax identification number).      |\r\n| Collections         | String | Set the collection separated by comma allowed to the buyer organization.                       |\r\n| Price Tables        | String | Set the price tables separated by comma allowed to the buyer organization.                     |\r\n| Payment Terms       | String | Set the payment terms separated by comma allowed to the buyer organization.                    |\r\n| Trade Policies      | String | Set the trade policies separated by comma allowed to the buyer organization.                   |\r\n| Sellers             | String | Set the Sellers separated by comma allowed to the buyer organization.                          |\r\n\r\n### Cost Centers Tab\r\n\r\nFor organizations with multiple cost centers. You don't need to fill this information if the buyer organization has only one cost center.\r\n\r\n| Field             | Type   | Description                                                                                   |\r\n|-------------------|--------|-----------------------------------------------------------------------------------------------|\r\n| Buyer Org ID*     | String | A unique identifier for the buyer organization essential for tracking and future updates.     |\r\n| Cost Center ID*   | String | A unique identifier for the cost center essential for tracking and future updates.            |\r\n| Cost Center Name* | String | The name assigned to the cost center.                                                         |\r\n| Address Type*     | String | The classification of the address (e.g., residential, commercial).                            |\r\n| Postal Code*      | String | The postal code corresponding to the address.                                                 |\r\n| Street*           | String | The street name of the address.                                                               |\r\n| Number*           | String | The numerical identifier for the location (house/building number).                            |\r\n| Complement*       | String | Additional information regarding the address if any.                                          |\r\n| Neighborhood*     | String | The specific neighborhood of the address.                                                     |\r\n| City*             | String | The city where the address is located.                                                        |\r\n| State*            | String | The state where the address is situated.                                                      |\r\n| Country*          | String | The country of the address.                                                                   |\r\n| Receiver Name*    | String | The name of the individual who is the point of contact at the address.                       |\r\n| Phone Number*     | String | The contact number for the receiver.                                                          |\r\n| Business Document*| String | A document that contains essential business information (e.g., tax identification number).    |\r\n\r\n### Members Tab\r\n\r\nFor organization with multiple members. You don't need to fill this information if the buyer organization has only one member.\r\n\r\n| Field           | Type    | Description                                                                                          |\r\n|-----------------|---------|------------------------------------------------------------------------------------------------------|\r\n| Buyer Org ID*   | String  | A unique identifier linking the member to a specific buyer organization.                            |\r\n| Cost Center ID* | String  | An identifier linking the member to a specific cost center within the organization.                  |\r\n| Name*           | String  | The member's full name used for identification and communication.                                    |\r\n| Email*          | String  | The email address of the member serving as a primary point of contact for communication.             |\r\n| Role Id*        | GUID    | A unique identifier denoting the member's role within the organization.                             |\r\n| Can Impersonate | Boolean | A boolean field indicating if the member can impersonate another user within the system.\r\n\r\n## Index\r\n\r\n### Bulk import\r\n\r\n- `POST` [Uploading a file](https://developers.vtex.com/docs/api-reference/buyer-organizations#post-/api/b2b/import/buyer-orgs)\r\n- `GET` [Check progress](https://developers.vtex.com/docs/api-reference/buyer-organizations#get-/api/b2b/import/buyer-orgs/-importId-)\r\n- `POST` [Start the import](https://developers.vtex.com/docs/api-reference/buyer-organizations#post-/api/b2b/import/buyer-orgs/-importId-)\r\n- `POST` [Validate the file](https://developers.vtex.com/docs/api-reference/buyer-organizations#post-/api/b2b/import/buyer-orgs/validate/-importId-)\r\n\r\n### Common parameters in the documentation\r\n\r\n| Parameter name          | Description                                         |\r\n|-------------------------|-----------------------------------------------------|\r\n| {{accountName}}         | Store account name.                                |\r\n| {{environment}}         | The environment that will be called.               |\r\n| {{X-VTEX-API-AppKey}}   | Located in the headers of the requests, user authentication key. |\r\n| {{X-VTEX-API-AppToken}} | Located in the headers of the requests, authentication password. |",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://{accountName}.{environment}.com.br",
            "description": "VTEX server URL.",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL.",
                    "default": "apiexamples"
                },
                "environment": {
                    "description": "Environment to use. Used as part of the URL.",
                    "enum": [
                        "vtexcommercestable"
                    ],
                    "default": "vtexcommercestable"
                }
            }
        }
    ],
    "paths": {
        "/api/b2b/import/buyer-orgs": {
            "post": {
                "tags": [
                    "Bulk Import"
                ],
                "summary": "Uploading a file",
                "description": "This endpoint allows users upload a file for bulk import. The uploaded file should be in excel format and less than 50mb \r\n\r\n## Permissions\r\n\r\nAny user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| B2B | B2B General | **B2BBulkImport** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type-Multipart"
                    },
                    {
                        "$ref": "#/components/parameters/an"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "encoding": {},
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary",
                                        "description": "File to be uploaded.",
                                        "example": "file.xlsx"
                                    }
                                }
                            }
                        }
                    },
                    "required": false
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/file-data"
                                },
                                "example": {
                                    "accountName": "accountName",
                                    "importId": "3c3cba0a-8355-4812-ad4d-f4c0b32e2613",
                                    "importState": "Uploaded",
                                    "percentage": "0",
                                    "lastUpdateDate": "2023-10-05T16:40:11+00:00",
                                    "fileName": "file.xlsx"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/b2b/import/buyer-orgs/{importId}": {
            "get": {
                "tags": [
                    "Bulk Import"
                ],
                "summary": "Check progress",
                "description": "This endpoint checks the progress of file validation or import. After successfully initiating validation or import, you can track progress by sending a GET request to this endpoint \r\n\r\n## Permissions\r\n\r\nAny user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| B2B | B2B General | **B2BBulkImport** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/an"
                    },
                    {
                        "$ref": "#/components/parameters/importId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response containing the details of the file validation or import.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/file-data"
                                },
                                "examples": {
                                    "example1": {
                                        "summary": "Validation details.",
                                        "value": {
                                            "accountName": "accountName",
                                            "importId": "3c3cba0a-8355-4812-ad4d-f4c0b32e2613",
                                            "importState": "InValidation",
                                            "percentage": "0",
                                            "lastUpdateDate": "2023-10-05T16:40:11+00:00",
                                            "fileName": "file.xlsx"
                                        }
                                    },
                                    "example2": {
                                        "summary": "Import details.",
                                        "value": {
                                            "accountName": "accountName",
                                            "importId": "3c3cba0a-8355-4812-ad4d-f4c0b32e2613",
                                            "importState": "Completed",
                                            "percentage": "100",
                                            "lastUpdateDate": "2023-10-05T16:41:11+00:00",
                                            "fileName": "file.xlsx"
                                        }
                                    },
                                    "example3": {
                                        "summary": "Validation erros details.",
                                        "value": {
                                            "accountName": "accountName",
                                            "importId": "71411025-c7d9-4c9d-92b5-9bc70a1acdb7",
                                            "importState": "ValidationFailed",
                                            "percentage": "0",
                                            "lastUpdateDate": "2024-02-21T17:56:57+00:00",
                                            "fileName": "file.xlsx",
                                            "validationResult": {
                                                "isValid": false,
                                                "validationResult": [
                                                    {
                                                        "name": "Organizations",
                                                        "validRows": 0,
                                                        "invalidRows": 1
                                                    },
                                                    {
                                                        "name": "Cost Centers",
                                                        "validRows": 0,
                                                        "invalidRows": 0
                                                    },
                                                    {
                                                        "name": "Members",
                                                        "validRows": 0,
                                                        "invalidRows": 0
                                                    }
                                                ]
                                            }
                                        }
                                    },
                                    "example4": {
                                        "summary": "Import erros details.",
                                        "value": {
                                            "accountName": "accountName",
                                            "importId": "d51b1b09-b4f3-44a3-ad70-53b9c8fe35f4",
                                            "importState": "CompletedWithError",
                                            "percentage": "100",
                                            "lastUpdateDate": "2024-02-26T14:47:10+00:00",
                                            "fileName": "test-26-fev-bulk-import-error.xlsx",
                                            "importResult": {
                                                "imports": [
                                                    {
                                                        "name": "Organizations",
                                                        "importedRows": 2,
                                                        "rowsWithError": 1
                                                    }
                                                ],
                                                "reportDownloadLink": "https://host.com/files/accountName/d51b1b09-b4f3-44a3-ad70-53b9c8fe35f4/file-error_Report.xlsx"
                                            },
                                            "importedAt": "2024-02-26T14:47:05+00:00",
                                            "importedUserEmail": "user@host.com",
                                            "importedUserName": "user"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Bulk Import"
                ],
                "summary": "Start the import",
                "description": "Once the file is successfully uploaded and validated, you can call the start import API, to actually start the import. You just need to send a POST request to the following endpoint providing the importId returned by the validate/upload API \r\n\r\n## Permissions\r\n\r\nAny user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| B2B | B2B General | **B2BBulkImport** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/an"
                    },
                    {
                        "$ref": "#/components/parameters/importId"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/b2b/import/buyer-orgs/validate/{importId}": {
            "post": {
                "tags": [
                    "Bulk Import"
                ],
                "summary": "Validate the file",
                "description": "This endpoint starts the file content validation. Once the the file is successfully uploaded you can start the validation using the `importId` returned by the upload endpoint \r\n\r\n## Permissions\r\n\r\nAny user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| B2B | B2B General | **B2BBulkImport** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/an"
                    },
                    {
                        "$ref": "#/components/parameters/importId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/file-data"
                                },
                                "example": {
                                    "accountName": "accountName",
                                    "importId": "3c3cba0a-8355-4812-ad4d-f4c0b32e2613",
                                    "importState": "Uploaded",
                                    "percentage": "0",
                                    "lastUpdateDate": "2023-10-05T16:40:11+00:00",
                                    "fileName": "file.xlsx"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "parameters": {
            "Content-Type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Type of the content being sent.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "application/json"
                }
            },
            "Content-Type-Multipart": {
                "name": "Content-Type",
                "in": "header",
                "description": "Type of the content being sent.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "multipart/form-data"
                }
            },
            "an": {
                "name": "an",
                "in": "query",
                "description": "Name of your VTEX account.",
                "required": false,
                "style": "form",
                "schema": {
                    "type": "string",
                    "example": "exampleAccount"
                }
            },
            "accountName": {
                "name": "accountName",
                "in": "path",
                "required": true,
                "description": "Name of your VTEX account.",
                "schema": {
                    "type": "string",
                    "example": "apiexamples"
                }
            },
            "environment": {
                "name": "environment",
                "in": "path",
                "required": true,
                "description": "Environment to be used in the request.",
                "schema": {
                    "type": "string",
                    "default": "vtexcommercestable"
                }
            },
            "importId": {
                "name": "importId",
                "in": "path",
                "required": true,
                "description": "Unique identifier of the import.",
                "schema": {
                    "type": "string",
                    "example": "3c3cba0a-8355-4812-ad4d-f4c0b32e2613"
                }
            }
        },
        "schemas": {
            "file-data": {
                "type": "object",
                "description": "Object containing information about bulk import state.",
                "properties": {
                    "accountName": {
                        "type": "string",
                        "description": "Name of your VTEX account."
                    },
                    "importId": {
                        "type": "string",
                        "description": "Unique identifier of the import."
                    },
                    "importState": {
                        "type": "string",
                        "description": "Current state of the import. The possible values are:\n- `Uploaded` The file was successfully uploaded.\n- `InValidation` File validation is in progress.\n- `ReadyToImport` File validation completed; ready for import.\n- `Completed` File successfully imported.\n- `ValidationFailed` File validation failed.\n- `CompletedWithError` File import failed."
                    },
                    "percentage": {
                        "type": "string",
                        "description": "Completion percentage of the import."
                    },
                    "lastUpdateDate": {
                        "type": "string",
                        "description": "Date and time of the last update of the import."
                    },
                    "fileName": {
                        "type": "string",
                        "description": "Name of the file being imported."
                    },
                    "importResult": {
                        "type": "object",
                        "description": "Information about the outcome of the bulk import operation.",
                        "properties": {
                            "reportDownloadLink": {
                                "type": "string",
                                "description": "A link to download a detailed report on the outcome of the bulk import."
                            },
                            "imports": {
                                "type": "array",
                                "description": "Detailed information about the imported items.",
                                "items": {
                                    "type": "object",
                                    "description": "Object with detailed information.",
                                    "properties": {
                                        "name": {
                                            "type": "string",
                                            "description": "Unique identifier associated with the imported item."
                                        },
                                        "importedRows": {
                                            "type": "integer",
                                            "description": "Total number of lines successfully imported."
                                        },
                                        "rowsWithError": {
                                            "type": "integer",
                                            "description": "Total number of lines that encountered errors during import."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "validationResult": {
                        "type": "object",
                        "description": "Information about the result of bulk imported data validation.",
                        "properties": {
                            "isValid": {
                                "type": "boolean",
                                "description": "Indicates whether the bulk import operation was successful."
                            },
                            "validationResult": {
                                "type": "array",
                                "description": "Detailed information about the validation results.",
                                "items": {
                                    "type": "object",
                                    "description": "Object with detailed information.",
                                    "properties": {
                                        "name": {
                                            "type": "string",
                                            "description": "Unique identifier associated with the imported item."
                                        },
                                        "validRows": {
                                            "type": "integer",
                                            "description": "Total number of lines successfully validated."
                                        },
                                        "invalidRows": {
                                            "type": "integer",
                                            "description": "Number of imported lines that failed validation."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey",
                "description": "Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken",
                "description": "Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
            },
            "VtexIdclientAutCookie": {
                "type": "apiKey",
                "in": "header",
                "name": "VtexIdclientAutCookie",
                "description": "[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours."
            }
        }
    },
    "tags": [
        {
            "name": "Bulk Import"
        }
    ],
    "security": [
        {
            "appKey": [],
            "appToken": []
        },
        {
            "VtexIdclientAutCookie": []
        }
    ]
}