{
    "openapi": "3.0.0",
    "info": {
        "title": "Price Simulations API",
        "description": "> Check the new [Pricing onboarding guide](https://developers.vtex.com/docs/guides/pricing-overview). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about Pricing and is organized by focusing on the developer's journey. \r\n\r\nThe Price Simulations API allows you to configure custom price selectors for B2B stores, based on the context set by the [Orders Configuration app](https://developers.vtex.com/docs/guides/vtex-order-configuration).\r\n\r\n## Index\r\n\r\n### Custom Prices\r\n \r\n- `GET` [Get custom prices schema](https://developers.vtex.com/docs/api-reference/price-simulations#get-/_v/custom-prices/session/schema) \r\n- `POST` [Create or Update custom prices schema](https://developers.vtex.com/docs/api-reference/price-simulations#post-/_v/custom-prices/session/schema) \r\n\r\n### Session Management \r\n\r\n- `POST` [Update Order Configuration](https://developers.vtex.com/docs/api-reference/price-simulations#post-/sessions/) \r\n\r\n\r\n### Price Association\r\n \r\n- `GET` [Get price association by ID](https://developers.vtex.com/docs/api-reference/price-simulations#get-/_v/custom-prices/rules/-priceAssociationId-) \r\n- `PUT` [Update price association by ID](https://developers.vtex.com/docs/api-reference/price-simulations#put-/_v/custom-prices/rules/-priceAssociationId-) \r\n- `DELETE` [Disassociate price association by ID](https://developers.vtex.com/docs/api-reference/price-simulations#delete-/_v/custom-prices/rules/-priceAssociationId-)\r\n- `POST` [Create price association](https://developers.vtex.com/docs/api-reference/price-simulations#post-/_v/custom-prices/rules) \r\n\r\n## Common parameters in the documentation\r\n\r\n| Parameter name | Description |\r\n| - | - |\r\n| `{{accountName}}` | Store account name |\r\n| `{{environment}}` | The environment that will be called. Change for vtexcommercestable or vtexcommmercebeta |\r\n| `{{X-VTEX-API-AppKey}}` | Located in the headers of the requests, user authentication key |\r\n| `{{X-VTEX-API-AppToken}}` | Located in the headers of the requests, authentication password |",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://{accountName}.{environment}.com.br",
            "description": "VTEX server URL.",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL",
                    "default": "apiexamples"
                },
                "environment": {
                    "description": "Environment to use. Used as part of the URL.",
                    "enum": [
                        "vtexcommercestable"
                    ],
                    "default": "vtexcommercestable"
                }
            }
        }
    ],
    "paths": {
        "/_v/custom-prices/session/schema": {
            "get": {
                "summary": "Get custom prices schema",
                "operationId": "getCustomPricesSchema",
                "tags": [
                    "Custom Prices"
                ],
                "description": "Retrieves all custom prices for all shopping scenarios.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "title": "Request body",
                                    "required": [
                                        "fields"
                                    ],
                                    "properties": {
                                        "fields": {
                                            "type": "array",
                                            "title": "fields",
                                            "description": "Order Configuration criteria.",
                                            "items": {
                                                "type": "object",
                                                "description": "Object with order configuration criteria.",
                                                "required": [
                                                    "name",
                                                    "type"
                                                ],
                                                "properties": {
                                                    "name": {
                                                        "type": "string",
                                                        "title": "name",
                                                        "description": "Criteria name."
                                                    },
                                                    "type": {
                                                        "type": "string",
                                                        "title": "type",
                                                        "description": "Criteria type."
                                                    }
                                                }
                                            }
                                        },
                                        "useEmail": {
                                            "type": "boolean",
                                            "title": "useEmail",
                                            "description": "If the custom price should use the user's email to validate it."
                                        }
                                    }
                                },
                                "example": {
                                    "$ref": "#/components/examples/OrderConfigExample/value"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Create or update custom prices schema",
                "operationId": "createOrUpdateCustomPricesSchema",
                "tags": [
                    "Custom Prices"
                ],
                "description": "Creates a new custom price for a shopping scenario or updates an existing one.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "title": "Request body",
                                "required": [
                                    "fields"
                                ],
                                "properties": {
                                    "fields": {
                                        "type": "array",
                                        "title": "fields",
                                        "description": "Order Configuration criteria.",
                                        "items": {
                                            "type": "object",
                                            "description": "Object with order configuration criteria.",
                                            "required": [
                                                "name",
                                                "type"
                                            ],
                                            "properties": {
                                                "name": {
                                                    "type": "string",
                                                    "title": "name",
                                                    "description": "Criteria name.",
                                                    "example": "orderType"
                                                },
                                                "type": {
                                                    "type": "string",
                                                    "title": "type",
                                                    "description": "Criteria type.",
                                                    "example": "string"
                                                }
                                            }
                                        }
                                    },
                                    "useEmail": {
                                        "type": "boolean",
                                        "title": "useEmail",
                                        "description": "If the custom price should use the user's email to validate it.",
                                        "example": true
                                    }
                                }
                            },
                            "example": {
                                "$ref": "#/components/examples/OrderConfigExample/value"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "title": "Request body",
                                    "required": [
                                        "fields"
                                    ],
                                    "properties": {
                                        "fields": {
                                            "type": "array",
                                            "title": "fields",
                                            "description": "Order Configuration criteria.",
                                            "items": {
                                                "type": "object",
                                                "description": "Object with order configuration criteria.",
                                                "required": [
                                                    "name",
                                                    "type"
                                                ],
                                                "properties": {
                                                    "name": {
                                                        "type": "string",
                                                        "title": "name",
                                                        "description": "Criteria name."
                                                    },
                                                    "type": {
                                                        "type": "string",
                                                        "title": "type",
                                                        "description": "Criteria type."
                                                    }
                                                }
                                            }
                                        },
                                        "useEmail": {
                                            "type": "boolean",
                                            "title": "useEmail",
                                            "description": "If the custom price should use the user's email to validate it."
                                        }
                                    }
                                },
                                "example": {
                                    "$ref": "#/components/examples/OrderConfigExample/value"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/sessions": {
            "description": "Every time you edit a configuration value set on the Custom Prices session, you must use this endpoint to update the Order Configuration.",
            "post": {
                "summary": "Update order configuration",
                "operationId": "updateOrderConfiguration",
                "tags": [
                    "Session Management"
                ],
                "description": "Updates the Order Configuration. You should use this route every time you edit a configuration value.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "title": "Request body",
                                "required": [
                                    "fields"
                                ],
                                "properties": {
                                    "fields": {
                                        "type": "array",
                                        "title": "fields",
                                        "description": "Order Configuration criteria.",
                                        "items": {
                                            "type": "object",
                                            "description": "Object with order configuration criteria.",
                                            "required": [
                                                "name",
                                                "type"
                                            ],
                                            "properties": {
                                                "name": {
                                                    "type": "string",
                                                    "title": "name",
                                                    "description": "Criteria name.",
                                                    "example": "orderType"
                                                },
                                                "type": {
                                                    "type": "string",
                                                    "title": "type",
                                                    "description": "Criteria type.",
                                                    "example": "string"
                                                }
                                            }
                                        }
                                    },
                                    "useEmail": {
                                        "type": "boolean",
                                        "title": "useEmail",
                                        "description": "If the custom price should use the user's email to validate it.",
                                        "example": true
                                    }
                                }
                            },
                            "example": {
                                "$ref": "#/components/examples/OrderConfigExample/value"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "title": "Request body",
                                    "required": [
                                        "public"
                                    ],
                                    "properties": {
                                        "fields": {
                                            "type": "array",
                                            "title": "public",
                                            "description": "Array containing the object to register session criteria.",
                                            "items": {
                                                "type": "object",
                                                "description": "Object with session criteria.",
                                                "required": [
                                                    "name"
                                                ],
                                                "properties": {
                                                    "customSessionKeys": {
                                                        "type": "object",
                                                        "title": "customSessionKeys",
                                                        "description": "Contains every schema criteria."
                                                    }
                                                }
                                            }
                                        },
                                        "value": {
                                            "type": "string",
                                            "title": "value",
                                            "description": "Order Configuration criteria. This is a serialized JSON object."
                                        }
                                    }
                                },
                                "example": {
                                    "public": [
                                        {
                                            "name": "customSessionKeys",
                                            "type": "object"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/_v/custom-prices/rules/{priceAssociationId}": {
            "description": "Use these routes to associate a shopping scenario, created at the Custom Price session, to a specific price table.",
            "get": {
                "summary": "Get price association by ID",
                "operationId": "getPriceAssociation",
                "tags": [
                    "Price Association"
                ],
                "description": "Retrieves price association for a shopping scenario by its ID.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "name": "priceAssociationId",
                        "in": "path",
                        "required": true,
                        "description": "Price Association unique identifier",
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "id",
                                        "pricetable"
                                    ],
                                    "properties": {
                                        "id": {
                                            "type": "integer",
                                            "title": "id",
                                            "description": "Price association ID."
                                        },
                                        "orderType": {
                                            "type": "string",
                                            "title": "orderType",
                                            "description": "Order type."
                                        },
                                        "state": {
                                            "type": "string",
                                            "title": "state",
                                            "description": "State of the shipping address."
                                        },
                                        "pricetable": {
                                            "type": "string",
                                            "title": "pricetable",
                                            "description": "Name of the Price Table associated with the scenario."
                                        },
                                        "email": {
                                            "title": "email",
                                            "type": "string",
                                            "description": "User's email."
                                        }
                                    }
                                },
                                "example": {
                                    "id": 0,
                                    "orderType": "orderType",
                                    "state": "Rio de Janeiro",
                                    "pricetable": "pricetable1",
                                    "email": "youremail@email.com"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Update price association by ID",
                "operationId": "updatePriceAssociation",
                "tags": [
                    "Price Association"
                ],
                "description": "Updates a price association for a shopping scenario by its ID.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "name": "priceAssociationId",
                        "in": "path",
                        "required": true,
                        "description": "Price Association unique identifier",
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "id",
                                        "pricetable"
                                    ],
                                    "properties": {
                                        "id": {
                                            "type": "integer",
                                            "title": "id",
                                            "description": "Price association ID.",
                                            "example": 0
                                        },
                                        "orderType": {
                                            "type": "string",
                                            "title": "orderType",
                                            "description": "Order type."
                                        },
                                        "state": {
                                            "type": "string",
                                            "title": "state",
                                            "description": "Delivery location."
                                        },
                                        "pricetable": {
                                            "type": "string",
                                            "title": "pricetable",
                                            "description": "Name of the Price Table associated with the scenario."
                                        },
                                        "email": {
                                            "type": "string",
                                            "title": "email",
                                            "description": "User's email."
                                        }
                                    }
                                },
                                "example": {
                                    "id": 0,
                                    "orderType": "orderType",
                                    "state": "Rio de Janeiro",
                                    "pricetable": "pricetable1",
                                    "email": "youraccount@email.com"
                                }
                            }
                        }
                    }
                },
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "title": "Request body",
                                "required": [
                                    "orderType",
                                    "state",
                                    "pricetable"
                                ],
                                "properties": {
                                    "orderType": {
                                        "type": "string",
                                        "title": "orderType",
                                        "description": "Order type.",
                                        "example": "orderType"
                                    },
                                    "state": {
                                        "type": "string",
                                        "title": "state",
                                        "description": "State of the shipping address.",
                                        "example": "RJ"
                                    },
                                    "pricetable": {
                                        "type": "string",
                                        "title": "pricetable",
                                        "description": "Name of the Price Table associated with the scenario.",
                                        "example": "pricetable1"
                                    }
                                }
                            },
                            "example": {
                                "orderType": "orderType",
                                "state": "RJ",
                                "pricetable": "pricetable1"
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Disassociate price association by ID",
                "operationId": "deletePriceAssociation",
                "tags": [
                    "Price Association"
                ],
                "description": "Disassociates a price association from a shopping scenario by its ID.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "name": "priceAssociationId",
                        "in": "path",
                        "required": true,
                        "description": "Price Association unique identifier.",
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string",
                                    "description": "Message confirming the deletion of the price association."
                                },
                                "example": "Rule deleted with success: custom_prices-5dc4f3d6-dda6-11ea-835b-12d97a7637bf"
                            }
                        }
                    }
                }
            }
        },
        "/_v/custom-prices/rules": {
            "post": {
                "summary": "Create price association",
                "operationId": "createPriceAssociation",
                "tags": [
                    "Price Association"
                ],
                "description": "Creates a new price association for a shopping scenario.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": [
                                    "pricetable"
                                ],
                                "properties": {
                                    "orderType": {
                                        "type": "string",
                                        "title": "orderType",
                                        "description": "Order type.",
                                        "example": "orderType1"
                                    },
                                    "state": {
                                        "type": "string",
                                        "title": "state",
                                        "description": "State of the shipping address.",
                                        "example": "Rio de Janeiro"
                                    },
                                    "pricetable": {
                                        "type": "string",
                                        "title": "pricetable",
                                        "description": "Name of the Price Table associated with the scenario.",
                                        "example": "pricetable1"
                                    },
                                    "email": {
                                        "type": "string",
                                        "title": "email",
                                        "description": "User's email.",
                                        "example": "youremail@email.com"
                                    }
                                }
                            },
                            "example": {
                                "orderType": "string",
                                "state": "Rio de Janeiro",
                                "pricetable": "pricetable1",
                                "email": "youremail@email.com"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "id",
                                        "pricetable"
                                    ],
                                    "properties": {
                                        "id": {
                                            "type": "integer",
                                            "title": "id",
                                            "description": "Price association ID."
                                        },
                                        "orderType": {
                                            "type": "string",
                                            "title": "orderType",
                                            "description": "Order type."
                                        },
                                        "state": {
                                            "type": "string",
                                            "title": "state",
                                            "description": "State of the shipping address."
                                        },
                                        "pricetable": {
                                            "type": "string",
                                            "title": "pricetable",
                                            "description": "Name of the Price Table associated with the scenario."
                                        },
                                        "email": {
                                            "type": "string",
                                            "title": "email",
                                            "description": "User's email."
                                        }
                                    }
                                },
                                "example": {
                                    "id": 0,
                                    "orderType": "orderType",
                                    "state": "Rio de Janeiro",
                                    "pricetable": "pricetable1",
                                    "email": "youremail@email.com"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey",
                "description": "Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken",
                "description": "Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
            },
            "VtexIdclientAutCookie": {
                "type": "apiKey",
                "in": "header",
                "name": "VtexIdclientAutCookie",
                "description": "[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours."
            }
        },
        "parameters": {
            "Content-Type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Type of the content being sent.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "application/json"
                }
            },
            "Accept": {
                "name": "Accept",
                "in": "header",
                "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "application/json"
                }
            }
        },
        "examples": {
            "OrderConfigExample": {
                "value": {
                    "fields": [
                        {
                            "name": "orderType",
                            "type": "string"
                        },
                        {
                            "name": "state",
                            "type": "string"
                        }
                    ],
                    "useEmail": true
                }
            }
        }
    },
    "tags": [
        {
            "name": "Session Management"
        },
        {
            "name": "Custom Prices"
        },
        {
            "name": "Price Association"
        }
    ],
    "security": [
        {
            "appKey": [],
            "appToken": []
        },
        {
            "VtexIdclientAutCookie": []
        }
    ]
}